# Cloudflare Pages Configuration for Next.js

name = "aidevelo-ai"
compatibility_date = "2024-12-19"

# Pages configuration - specify output directory
# For Next.js with Cloudflare Pages
pages_build_output_dir = ".vercel/output/static"
